### ISSUE TITLE
README update due to Github security change

### ISSUE THREAD

**Issue by Vuologist** [Baseflow/baseflow_plugin_template#3]
Hi,

While trying to setup the example geolocation flutter app, I realized I needed this package. I was getting git issues while following the readme when it came to adding the dependency. Can the readme be updated?

This fixed the issue:
```
dependencies:
  baseflow_plugin_template:
    git:
      # From
      url: git://github.com/Baseflow/baseflow_plugin_template.git
      # To
      url: https://github.com/Baseflow/baseflow_plugin_template.git
      ref: v2.0.0-nullsafety
```
Related link: https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported
